name: Send Discord Message

on:
  schedule:
    # Runs every 2 hours
    - cron: '0 */2 * * *'

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Make the script executable (optional)
        run: chmod +x pokeroll.py

      - name: Run the script
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: python pokeroll.py || exit 1